config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/analytics", to: "analytics#index"
  get "/my_analytics", to: "analytics#show"
  
  resources :pizzas
  resources :users, only: [:create]
  
  get "/", to: redirect("/pizzas")
  
  get "signup", to: "users#new"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "login", to: "sessions#destroy"

  get "order", to: "orders#order"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YumYum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/2ebbc8365f.js"></script>
  
    </head>

  <body>

  <nav class="nav_bar">
    <h1 id="logo">Pizza Gut</h1>
    <div class="nav_buttons">
      <% if @user && @user.id %>
        <%= link_to new_pizza_path do %>
          <i class="fas fa-pizza-slice fa-2x" alt="pizza icon" style="color: salmon;" ><%= button_to "Order New Pizza", new_pizza_path, method: :get %></i>
        <% end %>
      <% end %>
      <%= link_to pizzas_path do %>
        <i class="fas fa-pizza-slice fa-2x" alt="pizza icon" style="color: salmon;"><%= button_to "Check All Pizzas", pizzas_path, method: :get %></i>
      <% end %>
      <% if @user && @user.id %>
        <%= link_to "/my_analytics" do %>
          <i class="fas fa-chart-pie fa-2x" style="color: salmon;"><%= button_to "My Analytics", "/my_analytics", method: :get %></i>
        <% end %>
        <%= link_to "/analytics" do %>
          <i class="fas fa-chart-pie fa-2x" style="color: salmon;"><%= button_to "Analytics", "/analytics", method: :get %></i>
        <% end %>
          <%= link_to login_path, method: :delete do %>
        <i class="fas fa-user-alt-slash fa-2x" style="color: salmon;"><%= button_to "Logout", login_path, method: :delete %></i>
        <% end %>
      <% else %>
        <%= link_to signup_path do %>
          <i class="fas fa-user-plus fa-2x" style="color: salmon;"><%= button_to "Signup", signup_path, method: :get %></i>
        <% end %>
        <%= link_to login_path do %>
          <i class="fas fa-sign-in-alt fa-2x" style="color: salmon;"><%= button_to "Login", login_path, method: :get %></i>
        <% end %>
      <% end %>
    </div>
  </nav>
    <br> <%= yield %>

    
  </body>
</html>